### ISSUE TITLE
您好，远程仓库暂未找到最新1.6.2版本

### ISSUE THREAD

**Issue by mklp** [houbb/opencc4j#29]
![image](https://user-images.githubusercontent.com/40748963/128814884-7194de28-b3c4-4865-b1b3-6d6000e3aabf.png)

**Comment by houbb** [comment]
感谢提醒。昨晚太晚忘记了，你在试下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mklp ***@***.***&gt;
发送时间: 2021年8月10日 13:49
收件人: houbb/opencc4j ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[houbb/opencc4j] 您好，远程仓库暂未找到最新1.6.2版本 (#29)





 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mklp** [comment]
ok
