### ISSUE TITLE
可否支持更改字詞設定?

### ISSUE THREAD

**Issue by jackychu0830** [houbb/opencc4j#30]
目前代碼裡定只讀取 STPhrases.txt
照 OpenCC 的規格，是能把字詞轉換成台灣或香港在地的用語
不知可否支持讓使用者自行設定呢？

**Comment by jackychu0830** [comment]
比如 open 提供的線上 demo 能選擇不同的用語
https://opencc.byvoid.com

**Comment by houbb** [comment]
可以的，后面我加一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jacky Chu ***@***.***&gt;
发送时间: 2021年8月11日 09:03
收件人: houbb/opencc4j ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[houbb/opencc4j] 可否支持更改字詞設定? (#30)





 
目前代碼裡定只讀取 STPhrases.txt
 照 OpenCC 的規格，是能把字詞轉換成台灣或香港在地的用語
 不知可否支持讓使用者自行設定呢？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by houbb** [comment]
v1.7.0 已添加支持，并且内置了台湾地区的语言转换。
